import { Component, ElementRef, ViewChild } from '@angular/core';
import { Router } from '@angular/router';

/**
 * Angular @Component generated by cli
 */
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  /**
   * Title of site
   */
  title = 'My Messenger';

  constructor(private router: Router){}

  /*
  * Get user from session storage, if there is no user, user will equal null
  */ 
  user = sessionStorage.getItem("User");

  /**
   * Angular @ViewChild Decorator
   */
  @ViewChild('navbar_menu') navbar_menu: ElementRef<HTMLLIElement> | undefined;

  @ViewChild('search_bar') search_bar: ElementRef<HTMLLIElement> | undefined;

  goLogin(){
    this.router.navigate(['/login']);
  }

  goSignUp(){
    this.router.navigate(['/sign-up']);
  }

  goHome(){
    this.router.navigate(['main-screen']);
  }
  /**
   * Boolean value toggled: Is navbar-mobile toggled?
   */
  toggled = false;

  /**
   * Function to toggle menu on mobile navbar
   */
  toggle(){
    if(this.toggled == false){
      this.navbar_menu?.nativeElement.classList.add("is-active");
      this.toggled = true;
    }else{
      this.navbar_menu?.nativeElement.classList.remove("is-active");
      this.toggled = false;
    }
    console.log("toggled navbar!");
  }

}